# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResocaMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResocaMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13ResocaMessage.proto\"\x8c\x04\n\rResocaMessage\x12/\n\x0bmessageType\x18\x01 \x01(\x0e\x32\x1a.ResocaMessage.MessageType\x12\x11\n\tinterface\x18\x02 \x01(\t\x12)\n\x08\x63\x61nFrame\x18\x03 \x01(\x0b\x32\x17.ResocaMessage.CanFrame\x12-\n\nresocaInfo\x18\x04 \x01(\x0b\x32\x19.ResocaMessage.ResocaInfo\x1a\x31\n\nResocaInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\ninterfaces\x18\x02 \x03(\t\x1a\x9c\x01\n\x08\x43\x61nFrame\x12\r\n\x05\x63\x61nID\x18\x01 \x01(\r\x12\x0f\n\x07isCanFD\x18\x02 \x01(\x08\x12\x12\n\nisEFFFRAME\x18\x03 \x01(\x08\x12\x12\n\nisRTRFRAME\x18\x04 \x01(\x08\x12\x12\n\nisERRFRAME\x18\x05 \x01(\x08\x12\x12\n\nisCanFDESI\x18\x06 \x01(\x08\x12\x12\n\nisCanFDBRS\x18\x07 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\"\x8a\x01\n\x0bMessageType\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x12\x08\n\x04PONG\x10\x02\x12\x08\n\x04PING\x10\x03\x12\x0f\n\x0bRESOCA_INFO\x10\x04\x12\x10\n\x0cIF_CONNECTED\x10\x05\x12\x13\n\x0fIF_DISCONNECTED\x10\x06\x12\x0e\n\nMESSAGE_RX\x10\x07\x12\x0e\n\nMESSAGE_TX\x10\x08\x62\x06proto3'
)



_RESOCAMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='ResocaMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PONG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOCA_INFO', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_CONNECTED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IF_DISCONNECTED', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_RX', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_TX', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=410,
  serialized_end=548,
)
_sym_db.RegisterEnumDescriptor(_RESOCAMESSAGE_MESSAGETYPE)


_RESOCAMESSAGE_RESOCAINFO = _descriptor.Descriptor(
  name='ResocaInfo',
  full_name='ResocaMessage.ResocaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ResocaMessage.ResocaInfo.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interfaces', full_name='ResocaMessage.ResocaInfo.interfaces', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=248,
)

_RESOCAMESSAGE_CANFRAME = _descriptor.Descriptor(
  name='CanFrame',
  full_name='ResocaMessage.CanFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canID', full_name='ResocaMessage.CanFrame.canID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCanFD', full_name='ResocaMessage.CanFrame.isCanFD', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isEFFFRAME', full_name='ResocaMessage.CanFrame.isEFFFRAME', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRTRFRAME', full_name='ResocaMessage.CanFrame.isRTRFRAME', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isERRFRAME', full_name='ResocaMessage.CanFrame.isERRFRAME', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCanFDESI', full_name='ResocaMessage.CanFrame.isCanFDESI', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCanFDBRS', full_name='ResocaMessage.CanFrame.isCanFDBRS', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ResocaMessage.CanFrame.data', index=7,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=407,
)

_RESOCAMESSAGE = _descriptor.Descriptor(
  name='ResocaMessage',
  full_name='ResocaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='ResocaMessage.messageType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface', full_name='ResocaMessage.interface', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canFrame', full_name='ResocaMessage.canFrame', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resocaInfo', full_name='ResocaMessage.resocaInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESOCAMESSAGE_RESOCAINFO, _RESOCAMESSAGE_CANFRAME, ],
  enum_types=[
    _RESOCAMESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=548,
)

_RESOCAMESSAGE_RESOCAINFO.containing_type = _RESOCAMESSAGE
_RESOCAMESSAGE_CANFRAME.containing_type = _RESOCAMESSAGE
_RESOCAMESSAGE.fields_by_name['messageType'].enum_type = _RESOCAMESSAGE_MESSAGETYPE
_RESOCAMESSAGE.fields_by_name['canFrame'].message_type = _RESOCAMESSAGE_CANFRAME
_RESOCAMESSAGE.fields_by_name['resocaInfo'].message_type = _RESOCAMESSAGE_RESOCAINFO
_RESOCAMESSAGE_MESSAGETYPE.containing_type = _RESOCAMESSAGE
DESCRIPTOR.message_types_by_name['ResocaMessage'] = _RESOCAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResocaMessage = _reflection.GeneratedProtocolMessageType('ResocaMessage', (_message.Message,), {

  'ResocaInfo' : _reflection.GeneratedProtocolMessageType('ResocaInfo', (_message.Message,), {
    'DESCRIPTOR' : _RESOCAMESSAGE_RESOCAINFO,
    '__module__' : 'ResocaMessage_pb2'
    # @@protoc_insertion_point(class_scope:ResocaMessage.ResocaInfo)
    })
  ,

  'CanFrame' : _reflection.GeneratedProtocolMessageType('CanFrame', (_message.Message,), {
    'DESCRIPTOR' : _RESOCAMESSAGE_CANFRAME,
    '__module__' : 'ResocaMessage_pb2'
    # @@protoc_insertion_point(class_scope:ResocaMessage.CanFrame)
    })
  ,
  'DESCRIPTOR' : _RESOCAMESSAGE,
  '__module__' : 'ResocaMessage_pb2'
  # @@protoc_insertion_point(class_scope:ResocaMessage)
  })
_sym_db.RegisterMessage(ResocaMessage)
_sym_db.RegisterMessage(ResocaMessage.ResocaInfo)
_sym_db.RegisterMessage(ResocaMessage.CanFrame)


# @@protoc_insertion_point(module_scope)
