// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResocaMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ResocaMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ResocaMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ResocaMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ResocaMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ResocaMessage_2eproto;
class ResocaMessage;
class ResocaMessageDefaultTypeInternal;
extern ResocaMessageDefaultTypeInternal _ResocaMessage_default_instance_;
class ResocaMessage_CanFrame;
class ResocaMessage_CanFrameDefaultTypeInternal;
extern ResocaMessage_CanFrameDefaultTypeInternal _ResocaMessage_CanFrame_default_instance_;
class ResocaMessage_ResocaInfo;
class ResocaMessage_ResocaInfoDefaultTypeInternal;
extern ResocaMessage_ResocaInfoDefaultTypeInternal _ResocaMessage_ResocaInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ResocaMessage* Arena::CreateMaybeMessage<::ResocaMessage>(Arena*);
template<> ::ResocaMessage_CanFrame* Arena::CreateMaybeMessage<::ResocaMessage_CanFrame>(Arena*);
template<> ::ResocaMessage_ResocaInfo* Arena::CreateMaybeMessage<::ResocaMessage_ResocaInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ResocaMessage_MessageType : int {
  ResocaMessage_MessageType_OK = 0,
  ResocaMessage_MessageType_ERR = 1,
  ResocaMessage_MessageType_PONG = 2,
  ResocaMessage_MessageType_PING = 3,
  ResocaMessage_MessageType_RESOCA_INFO = 4,
  ResocaMessage_MessageType_IF_CONNECTED = 5,
  ResocaMessage_MessageType_IF_DISCONNECTED = 6,
  ResocaMessage_MessageType_MESSAGE_RX = 7,
  ResocaMessage_MessageType_MESSAGE_TX = 8,
  ResocaMessage_MessageType_ResocaMessage_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ResocaMessage_MessageType_ResocaMessage_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ResocaMessage_MessageType_IsValid(int value);
constexpr ResocaMessage_MessageType ResocaMessage_MessageType_MessageType_MIN = ResocaMessage_MessageType_OK;
constexpr ResocaMessage_MessageType ResocaMessage_MessageType_MessageType_MAX = ResocaMessage_MessageType_MESSAGE_TX;
constexpr int ResocaMessage_MessageType_MessageType_ARRAYSIZE = ResocaMessage_MessageType_MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResocaMessage_MessageType_descriptor();
template<typename T>
inline const std::string& ResocaMessage_MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResocaMessage_MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResocaMessage_MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResocaMessage_MessageType_descriptor(), enum_t_value);
}
inline bool ResocaMessage_MessageType_Parse(
    const std::string& name, ResocaMessage_MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResocaMessage_MessageType>(
    ResocaMessage_MessageType_descriptor(), name, value);
}
// ===================================================================

class ResocaMessage_ResocaInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResocaMessage.ResocaInfo) */ {
 public:
  ResocaMessage_ResocaInfo();
  virtual ~ResocaMessage_ResocaInfo();

  ResocaMessage_ResocaInfo(const ResocaMessage_ResocaInfo& from);
  ResocaMessage_ResocaInfo(ResocaMessage_ResocaInfo&& from) noexcept
    : ResocaMessage_ResocaInfo() {
    *this = ::std::move(from);
  }

  inline ResocaMessage_ResocaInfo& operator=(const ResocaMessage_ResocaInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResocaMessage_ResocaInfo& operator=(ResocaMessage_ResocaInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResocaMessage_ResocaInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResocaMessage_ResocaInfo* internal_default_instance() {
    return reinterpret_cast<const ResocaMessage_ResocaInfo*>(
               &_ResocaMessage_ResocaInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResocaMessage_ResocaInfo& a, ResocaMessage_ResocaInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ResocaMessage_ResocaInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResocaMessage_ResocaInfo* New() const final {
    return CreateMaybeMessage<ResocaMessage_ResocaInfo>(nullptr);
  }

  ResocaMessage_ResocaInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResocaMessage_ResocaInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResocaMessage_ResocaInfo& from);
  void MergeFrom(const ResocaMessage_ResocaInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResocaMessage_ResocaInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResocaMessage.ResocaInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ResocaMessage_2eproto);
    return ::descriptor_table_ResocaMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInterfacesFieldNumber = 2,
    kVersionFieldNumber = 1,
  };
  // repeated string interfaces = 2;
  int interfaces_size() const;
  private:
  int _internal_interfaces_size() const;
  public:
  void clear_interfaces();
  const std::string& interfaces(int index) const;
  std::string* mutable_interfaces(int index);
  void set_interfaces(int index, const std::string& value);
  void set_interfaces(int index, std::string&& value);
  void set_interfaces(int index, const char* value);
  void set_interfaces(int index, const char* value, size_t size);
  std::string* add_interfaces();
  void add_interfaces(const std::string& value);
  void add_interfaces(std::string&& value);
  void add_interfaces(const char* value);
  void add_interfaces(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& interfaces() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_interfaces();
  private:
  const std::string& _internal_interfaces(int index) const;
  std::string* _internal_add_interfaces();
  public:

  // string version = 1;
  void clear_version();
  const std::string& version() const;
  void set_version(const std::string& value);
  void set_version(std::string&& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  std::string* mutable_version();
  std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // @@protoc_insertion_point(class_scope:ResocaMessage.ResocaInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> interfaces_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ResocaMessage_2eproto;
};
// -------------------------------------------------------------------

class ResocaMessage_CanFrame :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResocaMessage.CanFrame) */ {
 public:
  ResocaMessage_CanFrame();
  virtual ~ResocaMessage_CanFrame();

  ResocaMessage_CanFrame(const ResocaMessage_CanFrame& from);
  ResocaMessage_CanFrame(ResocaMessage_CanFrame&& from) noexcept
    : ResocaMessage_CanFrame() {
    *this = ::std::move(from);
  }

  inline ResocaMessage_CanFrame& operator=(const ResocaMessage_CanFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResocaMessage_CanFrame& operator=(ResocaMessage_CanFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResocaMessage_CanFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResocaMessage_CanFrame* internal_default_instance() {
    return reinterpret_cast<const ResocaMessage_CanFrame*>(
               &_ResocaMessage_CanFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ResocaMessage_CanFrame& a, ResocaMessage_CanFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(ResocaMessage_CanFrame* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResocaMessage_CanFrame* New() const final {
    return CreateMaybeMessage<ResocaMessage_CanFrame>(nullptr);
  }

  ResocaMessage_CanFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResocaMessage_CanFrame>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResocaMessage_CanFrame& from);
  void MergeFrom(const ResocaMessage_CanFrame& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResocaMessage_CanFrame* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResocaMessage.CanFrame";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ResocaMessage_2eproto);
    return ::descriptor_table_ResocaMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 10,
    kCanIDFieldNumber = 1,
    kIsCanFDFieldNumber = 2,
    kIsEFFFRAMEFieldNumber = 3,
    kIsRTRFRAMEFieldNumber = 4,
    kIsERRFRAMEFieldNumber = 5,
    kIsCanFDESIFieldNumber = 6,
    kIsCanFDBRSFieldNumber = 7,
  };
  // bytes data = 10;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint32 canID = 1;
  void clear_canid();
  ::PROTOBUF_NAMESPACE_ID::uint32 canid() const;
  void set_canid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_canid() const;
  void _internal_set_canid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool isCanFD = 2;
  void clear_iscanfd();
  bool iscanfd() const;
  void set_iscanfd(bool value);
  private:
  bool _internal_iscanfd() const;
  void _internal_set_iscanfd(bool value);
  public:

  // bool isEFFFRAME = 3;
  void clear_iseffframe();
  bool iseffframe() const;
  void set_iseffframe(bool value);
  private:
  bool _internal_iseffframe() const;
  void _internal_set_iseffframe(bool value);
  public:

  // bool isRTRFRAME = 4;
  void clear_isrtrframe();
  bool isrtrframe() const;
  void set_isrtrframe(bool value);
  private:
  bool _internal_isrtrframe() const;
  void _internal_set_isrtrframe(bool value);
  public:

  // bool isERRFRAME = 5;
  void clear_iserrframe();
  bool iserrframe() const;
  void set_iserrframe(bool value);
  private:
  bool _internal_iserrframe() const;
  void _internal_set_iserrframe(bool value);
  public:

  // bool isCanFDESI = 6;
  void clear_iscanfdesi();
  bool iscanfdesi() const;
  void set_iscanfdesi(bool value);
  private:
  bool _internal_iscanfdesi() const;
  void _internal_set_iscanfdesi(bool value);
  public:

  // bool isCanFDBRS = 7;
  void clear_iscanfdbrs();
  bool iscanfdbrs() const;
  void set_iscanfdbrs(bool value);
  private:
  bool _internal_iscanfdbrs() const;
  void _internal_set_iscanfdbrs(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ResocaMessage.CanFrame)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 canid_;
  bool iscanfd_;
  bool iseffframe_;
  bool isrtrframe_;
  bool iserrframe_;
  bool iscanfdesi_;
  bool iscanfdbrs_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ResocaMessage_2eproto;
};
// -------------------------------------------------------------------

class ResocaMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResocaMessage) */ {
 public:
  ResocaMessage();
  virtual ~ResocaMessage();

  ResocaMessage(const ResocaMessage& from);
  ResocaMessage(ResocaMessage&& from) noexcept
    : ResocaMessage() {
    *this = ::std::move(from);
  }

  inline ResocaMessage& operator=(const ResocaMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResocaMessage& operator=(ResocaMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResocaMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResocaMessage* internal_default_instance() {
    return reinterpret_cast<const ResocaMessage*>(
               &_ResocaMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ResocaMessage& a, ResocaMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ResocaMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResocaMessage* New() const final {
    return CreateMaybeMessage<ResocaMessage>(nullptr);
  }

  ResocaMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResocaMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResocaMessage& from);
  void MergeFrom(const ResocaMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResocaMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResocaMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ResocaMessage_2eproto);
    return ::descriptor_table_ResocaMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ResocaMessage_ResocaInfo ResocaInfo;
  typedef ResocaMessage_CanFrame CanFrame;

  typedef ResocaMessage_MessageType MessageType;
  static constexpr MessageType OK =
    ResocaMessage_MessageType_OK;
  static constexpr MessageType ERR =
    ResocaMessage_MessageType_ERR;
  static constexpr MessageType PONG =
    ResocaMessage_MessageType_PONG;
  static constexpr MessageType PING =
    ResocaMessage_MessageType_PING;
  static constexpr MessageType RESOCA_INFO =
    ResocaMessage_MessageType_RESOCA_INFO;
  static constexpr MessageType IF_CONNECTED =
    ResocaMessage_MessageType_IF_CONNECTED;
  static constexpr MessageType IF_DISCONNECTED =
    ResocaMessage_MessageType_IF_DISCONNECTED;
  static constexpr MessageType MESSAGE_RX =
    ResocaMessage_MessageType_MESSAGE_RX;
  static constexpr MessageType MESSAGE_TX =
    ResocaMessage_MessageType_MESSAGE_TX;
  static inline bool MessageType_IsValid(int value) {
    return ResocaMessage_MessageType_IsValid(value);
  }
  static constexpr MessageType MessageType_MIN =
    ResocaMessage_MessageType_MessageType_MIN;
  static constexpr MessageType MessageType_MAX =
    ResocaMessage_MessageType_MessageType_MAX;
  static constexpr int MessageType_ARRAYSIZE =
    ResocaMessage_MessageType_MessageType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MessageType_descriptor() {
    return ResocaMessage_MessageType_descriptor();
  }
  template<typename T>
  static inline const std::string& MessageType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MessageType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MessageType_Name.");
    return ResocaMessage_MessageType_Name(enum_t_value);
  }
  static inline bool MessageType_Parse(const std::string& name,
      MessageType* value) {
    return ResocaMessage_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kInterfaceFieldNumber = 2,
    kCanFrameFieldNumber = 3,
    kResocaInfoFieldNumber = 4,
    kMessageTypeFieldNumber = 1,
  };
  // string interface = 2;
  void clear_interface();
  const std::string& interface() const;
  void set_interface(const std::string& value);
  void set_interface(std::string&& value);
  void set_interface(const char* value);
  void set_interface(const char* value, size_t size);
  std::string* mutable_interface();
  std::string* release_interface();
  void set_allocated_interface(std::string* interface);
  private:
  const std::string& _internal_interface() const;
  void _internal_set_interface(const std::string& value);
  std::string* _internal_mutable_interface();
  public:

  // .ResocaMessage.CanFrame canFrame = 3;
  bool has_canframe() const;
  private:
  bool _internal_has_canframe() const;
  public:
  void clear_canframe();
  const ::ResocaMessage_CanFrame& canframe() const;
  ::ResocaMessage_CanFrame* release_canframe();
  ::ResocaMessage_CanFrame* mutable_canframe();
  void set_allocated_canframe(::ResocaMessage_CanFrame* canframe);
  private:
  const ::ResocaMessage_CanFrame& _internal_canframe() const;
  ::ResocaMessage_CanFrame* _internal_mutable_canframe();
  public:

  // .ResocaMessage.ResocaInfo resocaInfo = 4;
  bool has_resocainfo() const;
  private:
  bool _internal_has_resocainfo() const;
  public:
  void clear_resocainfo();
  const ::ResocaMessage_ResocaInfo& resocainfo() const;
  ::ResocaMessage_ResocaInfo* release_resocainfo();
  ::ResocaMessage_ResocaInfo* mutable_resocainfo();
  void set_allocated_resocainfo(::ResocaMessage_ResocaInfo* resocainfo);
  private:
  const ::ResocaMessage_ResocaInfo& _internal_resocainfo() const;
  ::ResocaMessage_ResocaInfo* _internal_mutable_resocainfo();
  public:

  // .ResocaMessage.MessageType messageType = 1;
  void clear_messagetype();
  ::ResocaMessage_MessageType messagetype() const;
  void set_messagetype(::ResocaMessage_MessageType value);
  private:
  ::ResocaMessage_MessageType _internal_messagetype() const;
  void _internal_set_messagetype(::ResocaMessage_MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:ResocaMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr interface_;
  ::ResocaMessage_CanFrame* canframe_;
  ::ResocaMessage_ResocaInfo* resocainfo_;
  int messagetype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ResocaMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResocaMessage_ResocaInfo

// string version = 1;
inline void ResocaMessage_ResocaInfo::clear_version() {
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResocaMessage_ResocaInfo::version() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.ResocaInfo.version)
  return _internal_version();
}
inline void ResocaMessage_ResocaInfo::set_version(const std::string& value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.ResocaInfo.version)
}
inline std::string* ResocaMessage_ResocaInfo::mutable_version() {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.ResocaInfo.version)
  return _internal_mutable_version();
}
inline const std::string& ResocaMessage_ResocaInfo::_internal_version() const {
  return version_.GetNoArena();
}
inline void ResocaMessage_ResocaInfo::_internal_set_version(const std::string& value) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResocaMessage_ResocaInfo::set_version(std::string&& value) {
  
  version_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResocaMessage.ResocaInfo.version)
}
inline void ResocaMessage_ResocaInfo::set_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResocaMessage.ResocaInfo.version)
}
inline void ResocaMessage_ResocaInfo::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResocaMessage.ResocaInfo.version)
}
inline std::string* ResocaMessage_ResocaInfo::_internal_mutable_version() {
  
  return version_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResocaMessage_ResocaInfo::release_version() {
  // @@protoc_insertion_point(field_release:ResocaMessage.ResocaInfo.version)
  
  return version_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResocaMessage_ResocaInfo::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:ResocaMessage.ResocaInfo.version)
}

// repeated string interfaces = 2;
inline int ResocaMessage_ResocaInfo::_internal_interfaces_size() const {
  return interfaces_.size();
}
inline int ResocaMessage_ResocaInfo::interfaces_size() const {
  return _internal_interfaces_size();
}
inline void ResocaMessage_ResocaInfo::clear_interfaces() {
  interfaces_.Clear();
}
inline std::string* ResocaMessage_ResocaInfo::add_interfaces() {
  // @@protoc_insertion_point(field_add_mutable:ResocaMessage.ResocaInfo.interfaces)
  return _internal_add_interfaces();
}
inline const std::string& ResocaMessage_ResocaInfo::_internal_interfaces(int index) const {
  return interfaces_.Get(index);
}
inline const std::string& ResocaMessage_ResocaInfo::interfaces(int index) const {
  // @@protoc_insertion_point(field_get:ResocaMessage.ResocaInfo.interfaces)
  return _internal_interfaces(index);
}
inline std::string* ResocaMessage_ResocaInfo::mutable_interfaces(int index) {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.ResocaInfo.interfaces)
  return interfaces_.Mutable(index);
}
inline void ResocaMessage_ResocaInfo::set_interfaces(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ResocaMessage.ResocaInfo.interfaces)
  interfaces_.Mutable(index)->assign(value);
}
inline void ResocaMessage_ResocaInfo::set_interfaces(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ResocaMessage.ResocaInfo.interfaces)
  interfaces_.Mutable(index)->assign(std::move(value));
}
inline void ResocaMessage_ResocaInfo::set_interfaces(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  interfaces_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ResocaMessage.ResocaInfo.interfaces)
}
inline void ResocaMessage_ResocaInfo::set_interfaces(int index, const char* value, size_t size) {
  interfaces_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ResocaMessage.ResocaInfo.interfaces)
}
inline std::string* ResocaMessage_ResocaInfo::_internal_add_interfaces() {
  return interfaces_.Add();
}
inline void ResocaMessage_ResocaInfo::add_interfaces(const std::string& value) {
  interfaces_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ResocaMessage.ResocaInfo.interfaces)
}
inline void ResocaMessage_ResocaInfo::add_interfaces(std::string&& value) {
  interfaces_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ResocaMessage.ResocaInfo.interfaces)
}
inline void ResocaMessage_ResocaInfo::add_interfaces(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  interfaces_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ResocaMessage.ResocaInfo.interfaces)
}
inline void ResocaMessage_ResocaInfo::add_interfaces(const char* value, size_t size) {
  interfaces_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ResocaMessage.ResocaInfo.interfaces)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ResocaMessage_ResocaInfo::interfaces() const {
  // @@protoc_insertion_point(field_list:ResocaMessage.ResocaInfo.interfaces)
  return interfaces_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ResocaMessage_ResocaInfo::mutable_interfaces() {
  // @@protoc_insertion_point(field_mutable_list:ResocaMessage.ResocaInfo.interfaces)
  return &interfaces_;
}

// -------------------------------------------------------------------

// ResocaMessage_CanFrame

// uint32 canID = 1;
inline void ResocaMessage_CanFrame::clear_canid() {
  canid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ResocaMessage_CanFrame::_internal_canid() const {
  return canid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ResocaMessage_CanFrame::canid() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.canID)
  return _internal_canid();
}
inline void ResocaMessage_CanFrame::_internal_set_canid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  canid_ = value;
}
inline void ResocaMessage_CanFrame::set_canid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_canid(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.canID)
}

// bool isCanFD = 2;
inline void ResocaMessage_CanFrame::clear_iscanfd() {
  iscanfd_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_iscanfd() const {
  return iscanfd_;
}
inline bool ResocaMessage_CanFrame::iscanfd() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isCanFD)
  return _internal_iscanfd();
}
inline void ResocaMessage_CanFrame::_internal_set_iscanfd(bool value) {
  
  iscanfd_ = value;
}
inline void ResocaMessage_CanFrame::set_iscanfd(bool value) {
  _internal_set_iscanfd(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isCanFD)
}

// bool isEFFFRAME = 3;
inline void ResocaMessage_CanFrame::clear_iseffframe() {
  iseffframe_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_iseffframe() const {
  return iseffframe_;
}
inline bool ResocaMessage_CanFrame::iseffframe() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isEFFFRAME)
  return _internal_iseffframe();
}
inline void ResocaMessage_CanFrame::_internal_set_iseffframe(bool value) {
  
  iseffframe_ = value;
}
inline void ResocaMessage_CanFrame::set_iseffframe(bool value) {
  _internal_set_iseffframe(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isEFFFRAME)
}

// bool isRTRFRAME = 4;
inline void ResocaMessage_CanFrame::clear_isrtrframe() {
  isrtrframe_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_isrtrframe() const {
  return isrtrframe_;
}
inline bool ResocaMessage_CanFrame::isrtrframe() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isRTRFRAME)
  return _internal_isrtrframe();
}
inline void ResocaMessage_CanFrame::_internal_set_isrtrframe(bool value) {
  
  isrtrframe_ = value;
}
inline void ResocaMessage_CanFrame::set_isrtrframe(bool value) {
  _internal_set_isrtrframe(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isRTRFRAME)
}

// bool isERRFRAME = 5;
inline void ResocaMessage_CanFrame::clear_iserrframe() {
  iserrframe_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_iserrframe() const {
  return iserrframe_;
}
inline bool ResocaMessage_CanFrame::iserrframe() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isERRFRAME)
  return _internal_iserrframe();
}
inline void ResocaMessage_CanFrame::_internal_set_iserrframe(bool value) {
  
  iserrframe_ = value;
}
inline void ResocaMessage_CanFrame::set_iserrframe(bool value) {
  _internal_set_iserrframe(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isERRFRAME)
}

// bool isCanFDESI = 6;
inline void ResocaMessage_CanFrame::clear_iscanfdesi() {
  iscanfdesi_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_iscanfdesi() const {
  return iscanfdesi_;
}
inline bool ResocaMessage_CanFrame::iscanfdesi() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isCanFDESI)
  return _internal_iscanfdesi();
}
inline void ResocaMessage_CanFrame::_internal_set_iscanfdesi(bool value) {
  
  iscanfdesi_ = value;
}
inline void ResocaMessage_CanFrame::set_iscanfdesi(bool value) {
  _internal_set_iscanfdesi(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isCanFDESI)
}

// bool isCanFDBRS = 7;
inline void ResocaMessage_CanFrame::clear_iscanfdbrs() {
  iscanfdbrs_ = false;
}
inline bool ResocaMessage_CanFrame::_internal_iscanfdbrs() const {
  return iscanfdbrs_;
}
inline bool ResocaMessage_CanFrame::iscanfdbrs() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.isCanFDBRS)
  return _internal_iscanfdbrs();
}
inline void ResocaMessage_CanFrame::_internal_set_iscanfdbrs(bool value) {
  
  iscanfdbrs_ = value;
}
inline void ResocaMessage_CanFrame::set_iscanfdbrs(bool value) {
  _internal_set_iscanfdbrs(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.isCanFDBRS)
}

// bytes data = 10;
inline void ResocaMessage_CanFrame::clear_data() {
  data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResocaMessage_CanFrame::data() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.CanFrame.data)
  return _internal_data();
}
inline void ResocaMessage_CanFrame::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.CanFrame.data)
}
inline std::string* ResocaMessage_CanFrame::mutable_data() {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.CanFrame.data)
  return _internal_mutable_data();
}
inline const std::string& ResocaMessage_CanFrame::_internal_data() const {
  return data_.GetNoArena();
}
inline void ResocaMessage_CanFrame::_internal_set_data(const std::string& value) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResocaMessage_CanFrame::set_data(std::string&& value) {
  
  data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResocaMessage.CanFrame.data)
}
inline void ResocaMessage_CanFrame::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResocaMessage.CanFrame.data)
}
inline void ResocaMessage_CanFrame::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResocaMessage.CanFrame.data)
}
inline std::string* ResocaMessage_CanFrame::_internal_mutable_data() {
  
  return data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResocaMessage_CanFrame::release_data() {
  // @@protoc_insertion_point(field_release:ResocaMessage.CanFrame.data)
  
  return data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResocaMessage_CanFrame::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:ResocaMessage.CanFrame.data)
}

// -------------------------------------------------------------------

// ResocaMessage

// .ResocaMessage.MessageType messageType = 1;
inline void ResocaMessage::clear_messagetype() {
  messagetype_ = 0;
}
inline ::ResocaMessage_MessageType ResocaMessage::_internal_messagetype() const {
  return static_cast< ::ResocaMessage_MessageType >(messagetype_);
}
inline ::ResocaMessage_MessageType ResocaMessage::messagetype() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.messageType)
  return _internal_messagetype();
}
inline void ResocaMessage::_internal_set_messagetype(::ResocaMessage_MessageType value) {
  
  messagetype_ = value;
}
inline void ResocaMessage::set_messagetype(::ResocaMessage_MessageType value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.messageType)
}

// string interface = 2;
inline void ResocaMessage::clear_interface() {
  interface_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResocaMessage::interface() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.interface)
  return _internal_interface();
}
inline void ResocaMessage::set_interface(const std::string& value) {
  _internal_set_interface(value);
  // @@protoc_insertion_point(field_set:ResocaMessage.interface)
}
inline std::string* ResocaMessage::mutable_interface() {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.interface)
  return _internal_mutable_interface();
}
inline const std::string& ResocaMessage::_internal_interface() const {
  return interface_.GetNoArena();
}
inline void ResocaMessage::_internal_set_interface(const std::string& value) {
  
  interface_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResocaMessage::set_interface(std::string&& value) {
  
  interface_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ResocaMessage.interface)
}
inline void ResocaMessage::set_interface(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  interface_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ResocaMessage.interface)
}
inline void ResocaMessage::set_interface(const char* value, size_t size) {
  
  interface_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ResocaMessage.interface)
}
inline std::string* ResocaMessage::_internal_mutable_interface() {
  
  return interface_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResocaMessage::release_interface() {
  // @@protoc_insertion_point(field_release:ResocaMessage.interface)
  
  return interface_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResocaMessage::set_allocated_interface(std::string* interface) {
  if (interface != nullptr) {
    
  } else {
    
  }
  interface_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), interface);
  // @@protoc_insertion_point(field_set_allocated:ResocaMessage.interface)
}

// .ResocaMessage.CanFrame canFrame = 3;
inline bool ResocaMessage::_internal_has_canframe() const {
  return this != internal_default_instance() && canframe_ != nullptr;
}
inline bool ResocaMessage::has_canframe() const {
  return _internal_has_canframe();
}
inline void ResocaMessage::clear_canframe() {
  if (GetArenaNoVirtual() == nullptr && canframe_ != nullptr) {
    delete canframe_;
  }
  canframe_ = nullptr;
}
inline const ::ResocaMessage_CanFrame& ResocaMessage::_internal_canframe() const {
  const ::ResocaMessage_CanFrame* p = canframe_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ResocaMessage_CanFrame*>(
      &::_ResocaMessage_CanFrame_default_instance_);
}
inline const ::ResocaMessage_CanFrame& ResocaMessage::canframe() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.canFrame)
  return _internal_canframe();
}
inline ::ResocaMessage_CanFrame* ResocaMessage::release_canframe() {
  // @@protoc_insertion_point(field_release:ResocaMessage.canFrame)
  
  ::ResocaMessage_CanFrame* temp = canframe_;
  canframe_ = nullptr;
  return temp;
}
inline ::ResocaMessage_CanFrame* ResocaMessage::_internal_mutable_canframe() {
  
  if (canframe_ == nullptr) {
    auto* p = CreateMaybeMessage<::ResocaMessage_CanFrame>(GetArenaNoVirtual());
    canframe_ = p;
  }
  return canframe_;
}
inline ::ResocaMessage_CanFrame* ResocaMessage::mutable_canframe() {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.canFrame)
  return _internal_mutable_canframe();
}
inline void ResocaMessage::set_allocated_canframe(::ResocaMessage_CanFrame* canframe) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete canframe_;
  }
  if (canframe) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      canframe = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, canframe, submessage_arena);
    }
    
  } else {
    
  }
  canframe_ = canframe;
  // @@protoc_insertion_point(field_set_allocated:ResocaMessage.canFrame)
}

// .ResocaMessage.ResocaInfo resocaInfo = 4;
inline bool ResocaMessage::_internal_has_resocainfo() const {
  return this != internal_default_instance() && resocainfo_ != nullptr;
}
inline bool ResocaMessage::has_resocainfo() const {
  return _internal_has_resocainfo();
}
inline void ResocaMessage::clear_resocainfo() {
  if (GetArenaNoVirtual() == nullptr && resocainfo_ != nullptr) {
    delete resocainfo_;
  }
  resocainfo_ = nullptr;
}
inline const ::ResocaMessage_ResocaInfo& ResocaMessage::_internal_resocainfo() const {
  const ::ResocaMessage_ResocaInfo* p = resocainfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ResocaMessage_ResocaInfo*>(
      &::_ResocaMessage_ResocaInfo_default_instance_);
}
inline const ::ResocaMessage_ResocaInfo& ResocaMessage::resocainfo() const {
  // @@protoc_insertion_point(field_get:ResocaMessage.resocaInfo)
  return _internal_resocainfo();
}
inline ::ResocaMessage_ResocaInfo* ResocaMessage::release_resocainfo() {
  // @@protoc_insertion_point(field_release:ResocaMessage.resocaInfo)
  
  ::ResocaMessage_ResocaInfo* temp = resocainfo_;
  resocainfo_ = nullptr;
  return temp;
}
inline ::ResocaMessage_ResocaInfo* ResocaMessage::_internal_mutable_resocainfo() {
  
  if (resocainfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::ResocaMessage_ResocaInfo>(GetArenaNoVirtual());
    resocainfo_ = p;
  }
  return resocainfo_;
}
inline ::ResocaMessage_ResocaInfo* ResocaMessage::mutable_resocainfo() {
  // @@protoc_insertion_point(field_mutable:ResocaMessage.resocaInfo)
  return _internal_mutable_resocainfo();
}
inline void ResocaMessage::set_allocated_resocainfo(::ResocaMessage_ResocaInfo* resocainfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resocainfo_;
  }
  if (resocainfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resocainfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, resocainfo, submessage_arena);
    }
    
  } else {
    
  }
  resocainfo_ = resocainfo;
  // @@protoc_insertion_point(field_set_allocated:ResocaMessage.resocaInfo)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ResocaMessage_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ResocaMessage_MessageType>() {
  return ::ResocaMessage_MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ResocaMessage_2eproto
