// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResocaMessage.proto

#include "ResocaMessage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_ResocaMessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_ResocaMessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto;
class ResocaMessage_ResocaInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResocaMessage_ResocaInfo> _instance;
} _ResocaMessage_ResocaInfo_default_instance_;
class ResocaMessage_CanFrameDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResocaMessage_CanFrame> _instance;
} _ResocaMessage_CanFrame_default_instance_;
class ResocaMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResocaMessage> _instance;
} _ResocaMessage_default_instance_;
static void InitDefaultsscc_info_ResocaMessage_ResocaMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ResocaMessage_default_instance_;
    new (ptr) ::ResocaMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ResocaMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ResocaMessage_ResocaMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ResocaMessage_ResocaMessage_2eproto}, {
      &scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto.base,
      &scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto.base,}};

static void InitDefaultsscc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ResocaMessage_CanFrame_default_instance_;
    new (ptr) ::ResocaMessage_CanFrame();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ResocaMessage_CanFrame::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto}, {}};

static void InitDefaultsscc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ResocaMessage_ResocaInfo_default_instance_;
    new (ptr) ::ResocaMessage_ResocaInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ResocaMessage_ResocaInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ResocaMessage_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_ResocaMessage_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ResocaMessage_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ResocaMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_ResocaInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_ResocaInfo, version_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_ResocaInfo, interfaces_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, canid_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, iscanfd_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, iseffframe_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, isrtrframe_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, iserrframe_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, iscanfdesi_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, iscanfdbrs_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage_CanFrame, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ResocaMessage, messagetype_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage, interface_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage, canframe_),
  PROTOBUF_FIELD_OFFSET(::ResocaMessage, resocainfo_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ResocaMessage_ResocaInfo)},
  { 7, -1, sizeof(::ResocaMessage_CanFrame)},
  { 20, -1, sizeof(::ResocaMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ResocaMessage_ResocaInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ResocaMessage_CanFrame_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ResocaMessage_default_instance_),
};

const char descriptor_table_protodef_ResocaMessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023ResocaMessage.proto\"\346\003\n\rResocaMessage\022"
  "/\n\013messageType\030\001 \001(\0162\032.ResocaMessage.Mes"
  "sageType\022\021\n\tinterface\030\002 \001(\t\022)\n\010canFrame\030"
  "\003 \001(\0132\027.ResocaMessage.CanFrame\022-\n\nresoca"
  "Info\030\004 \001(\0132\031.ResocaMessage.ResocaInfo\0321\n"
  "\nResocaInfo\022\017\n\007version\030\001 \001(\t\022\022\n\ninterfac"
  "es\030\002 \003(\t\032\234\001\n\010CanFrame\022\r\n\005canID\030\001 \001(\r\022\017\n\007"
  "isCanFD\030\002 \001(\010\022\022\n\nisEFFFRAME\030\003 \001(\010\022\022\n\nisR"
  "TRFRAME\030\004 \001(\010\022\022\n\nisERRFRAME\030\005 \001(\010\022\022\n\nisC"
  "anFDESI\030\006 \001(\010\022\022\n\nisCanFDBRS\030\007 \001(\010\022\014\n\004dat"
  "a\030\n \001(\014\"e\n\013MessageType\022\017\n\013RESOCA_INFO\020\000\022"
  "\020\n\014IF_CONNECTED\020\001\022\023\n\017IF_DISCONNECTED\020\002\022\016"
  "\n\nMESSAGE_RX\020\003\022\016\n\nMESSAGE_TX\020\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ResocaMessage_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ResocaMessage_2eproto_sccs[3] = {
  &scc_info_ResocaMessage_ResocaMessage_2eproto.base,
  &scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto.base,
  &scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ResocaMessage_2eproto_once;
static bool descriptor_table_ResocaMessage_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ResocaMessage_2eproto = {
  &descriptor_table_ResocaMessage_2eproto_initialized, descriptor_table_protodef_ResocaMessage_2eproto, "ResocaMessage.proto", 518,
  &descriptor_table_ResocaMessage_2eproto_once, descriptor_table_ResocaMessage_2eproto_sccs, descriptor_table_ResocaMessage_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_ResocaMessage_2eproto::offsets,
  file_level_metadata_ResocaMessage_2eproto, 3, file_level_enum_descriptors_ResocaMessage_2eproto, file_level_service_descriptors_ResocaMessage_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ResocaMessage_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ResocaMessage_2eproto), true);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResocaMessage_MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ResocaMessage_2eproto);
  return file_level_enum_descriptors_ResocaMessage_2eproto[0];
}
bool ResocaMessage_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ResocaMessage_MessageType ResocaMessage::RESOCA_INFO;
constexpr ResocaMessage_MessageType ResocaMessage::IF_CONNECTED;
constexpr ResocaMessage_MessageType ResocaMessage::IF_DISCONNECTED;
constexpr ResocaMessage_MessageType ResocaMessage::MESSAGE_RX;
constexpr ResocaMessage_MessageType ResocaMessage::MESSAGE_TX;
constexpr ResocaMessage_MessageType ResocaMessage::MessageType_MIN;
constexpr ResocaMessage_MessageType ResocaMessage::MessageType_MAX;
constexpr int ResocaMessage::MessageType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void ResocaMessage_ResocaInfo::InitAsDefaultInstance() {
}
class ResocaMessage_ResocaInfo::_Internal {
 public:
};

ResocaMessage_ResocaInfo::ResocaMessage_ResocaInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ResocaMessage.ResocaInfo)
}
ResocaMessage_ResocaInfo::ResocaMessage_ResocaInfo(const ResocaMessage_ResocaInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      interfaces_(from.interfaces_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_version().empty()) {
    version_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  // @@protoc_insertion_point(copy_constructor:ResocaMessage.ResocaInfo)
}

void ResocaMessage_ResocaInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto.base);
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ResocaMessage_ResocaInfo::~ResocaMessage_ResocaInfo() {
  // @@protoc_insertion_point(destructor:ResocaMessage.ResocaInfo)
  SharedDtor();
}

void ResocaMessage_ResocaInfo::SharedDtor() {
  version_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ResocaMessage_ResocaInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResocaMessage_ResocaInfo& ResocaMessage_ResocaInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResocaMessage_ResocaInfo_ResocaMessage_2eproto.base);
  return *internal_default_instance();
}


void ResocaMessage_ResocaInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ResocaMessage.ResocaInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  interfaces_.Clear();
  version_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* ResocaMessage_ResocaInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_version();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ResocaMessage.ResocaInfo.version"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string interfaces = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_interfaces();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ResocaMessage.ResocaInfo.interfaces"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResocaMessage_ResocaInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResocaMessage.ResocaInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string version = 1;
  if (this->version().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_version().data(), static_cast<int>(this->_internal_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ResocaMessage.ResocaInfo.version");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_version(), target);
  }

  // repeated string interfaces = 2;
  for (int i = 0, n = this->_internal_interfaces_size(); i < n; i++) {
    const auto& s = this->_internal_interfaces(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ResocaMessage.ResocaInfo.interfaces");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResocaMessage.ResocaInfo)
  return target;
}

size_t ResocaMessage_ResocaInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResocaMessage.ResocaInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string interfaces = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(interfaces_.size());
  for (int i = 0, n = interfaces_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      interfaces_.Get(i));
  }

  // string version = 1;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResocaMessage_ResocaInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ResocaMessage.ResocaInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ResocaMessage_ResocaInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResocaMessage_ResocaInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ResocaMessage.ResocaInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ResocaMessage.ResocaInfo)
    MergeFrom(*source);
  }
}

void ResocaMessage_ResocaInfo::MergeFrom(const ResocaMessage_ResocaInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResocaMessage.ResocaInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  interfaces_.MergeFrom(from.interfaces_);
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
}

void ResocaMessage_ResocaInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ResocaMessage.ResocaInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResocaMessage_ResocaInfo::CopyFrom(const ResocaMessage_ResocaInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResocaMessage.ResocaInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResocaMessage_ResocaInfo::IsInitialized() const {
  return true;
}

void ResocaMessage_ResocaInfo::InternalSwap(ResocaMessage_ResocaInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  interfaces_.InternalSwap(&other->interfaces_);
  version_.Swap(&other->version_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata ResocaMessage_ResocaInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResocaMessage_CanFrame::InitAsDefaultInstance() {
}
class ResocaMessage_CanFrame::_Internal {
 public:
};

ResocaMessage_CanFrame::ResocaMessage_CanFrame()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ResocaMessage.CanFrame)
}
ResocaMessage_CanFrame::ResocaMessage_CanFrame(const ResocaMessage_CanFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_data().empty()) {
    data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  ::memcpy(&canid_, &from.canid_,
    static_cast<size_t>(reinterpret_cast<char*>(&iscanfdbrs_) -
    reinterpret_cast<char*>(&canid_)) + sizeof(iscanfdbrs_));
  // @@protoc_insertion_point(copy_constructor:ResocaMessage.CanFrame)
}

void ResocaMessage_CanFrame::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto.base);
  data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&canid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&iscanfdbrs_) -
      reinterpret_cast<char*>(&canid_)) + sizeof(iscanfdbrs_));
}

ResocaMessage_CanFrame::~ResocaMessage_CanFrame() {
  // @@protoc_insertion_point(destructor:ResocaMessage.CanFrame)
  SharedDtor();
}

void ResocaMessage_CanFrame::SharedDtor() {
  data_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ResocaMessage_CanFrame::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResocaMessage_CanFrame& ResocaMessage_CanFrame::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResocaMessage_CanFrame_ResocaMessage_2eproto.base);
  return *internal_default_instance();
}


void ResocaMessage_CanFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:ResocaMessage.CanFrame)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&canid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&iscanfdbrs_) -
      reinterpret_cast<char*>(&canid_)) + sizeof(iscanfdbrs_));
  _internal_metadata_.Clear();
}

const char* ResocaMessage_CanFrame::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 canID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          canid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isCanFD = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          iscanfd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isEFFFRAME = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          iseffframe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isRTRFRAME = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          isrtrframe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isERRFRAME = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          iserrframe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isCanFDESI = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          iscanfdesi_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool isCanFDBRS = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          iscanfdbrs_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes data = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResocaMessage_CanFrame::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResocaMessage.CanFrame)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 canID = 1;
  if (this->canid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_canid(), target);
  }

  // bool isCanFD = 2;
  if (this->iscanfd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_iscanfd(), target);
  }

  // bool isEFFFRAME = 3;
  if (this->iseffframe() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_iseffframe(), target);
  }

  // bool isRTRFRAME = 4;
  if (this->isrtrframe() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_isrtrframe(), target);
  }

  // bool isERRFRAME = 5;
  if (this->iserrframe() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_iserrframe(), target);
  }

  // bool isCanFDESI = 6;
  if (this->iscanfdesi() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_iscanfdesi(), target);
  }

  // bool isCanFDBRS = 7;
  if (this->iscanfdbrs() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_iscanfdbrs(), target);
  }

  // bytes data = 10;
  if (this->data().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResocaMessage.CanFrame)
  return target;
}

size_t ResocaMessage_CanFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResocaMessage.CanFrame)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 10;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // uint32 canID = 1;
  if (this->canid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_canid());
  }

  // bool isCanFD = 2;
  if (this->iscanfd() != 0) {
    total_size += 1 + 1;
  }

  // bool isEFFFRAME = 3;
  if (this->iseffframe() != 0) {
    total_size += 1 + 1;
  }

  // bool isRTRFRAME = 4;
  if (this->isrtrframe() != 0) {
    total_size += 1 + 1;
  }

  // bool isERRFRAME = 5;
  if (this->iserrframe() != 0) {
    total_size += 1 + 1;
  }

  // bool isCanFDESI = 6;
  if (this->iscanfdesi() != 0) {
    total_size += 1 + 1;
  }

  // bool isCanFDBRS = 7;
  if (this->iscanfdbrs() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResocaMessage_CanFrame::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ResocaMessage.CanFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const ResocaMessage_CanFrame* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResocaMessage_CanFrame>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ResocaMessage.CanFrame)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ResocaMessage.CanFrame)
    MergeFrom(*source);
  }
}

void ResocaMessage_CanFrame::MergeFrom(const ResocaMessage_CanFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResocaMessage.CanFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.canid() != 0) {
    _internal_set_canid(from._internal_canid());
  }
  if (from.iscanfd() != 0) {
    _internal_set_iscanfd(from._internal_iscanfd());
  }
  if (from.iseffframe() != 0) {
    _internal_set_iseffframe(from._internal_iseffframe());
  }
  if (from.isrtrframe() != 0) {
    _internal_set_isrtrframe(from._internal_isrtrframe());
  }
  if (from.iserrframe() != 0) {
    _internal_set_iserrframe(from._internal_iserrframe());
  }
  if (from.iscanfdesi() != 0) {
    _internal_set_iscanfdesi(from._internal_iscanfdesi());
  }
  if (from.iscanfdbrs() != 0) {
    _internal_set_iscanfdbrs(from._internal_iscanfdbrs());
  }
}

void ResocaMessage_CanFrame::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ResocaMessage.CanFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResocaMessage_CanFrame::CopyFrom(const ResocaMessage_CanFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResocaMessage.CanFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResocaMessage_CanFrame::IsInitialized() const {
  return true;
}

void ResocaMessage_CanFrame::InternalSwap(ResocaMessage_CanFrame* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  data_.Swap(&other->data_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(canid_, other->canid_);
  swap(iscanfd_, other->iscanfd_);
  swap(iseffframe_, other->iseffframe_);
  swap(isrtrframe_, other->isrtrframe_);
  swap(iserrframe_, other->iserrframe_);
  swap(iscanfdesi_, other->iscanfdesi_);
  swap(iscanfdbrs_, other->iscanfdbrs_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResocaMessage_CanFrame::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResocaMessage::InitAsDefaultInstance() {
  ::_ResocaMessage_default_instance_._instance.get_mutable()->canframe_ = const_cast< ::ResocaMessage_CanFrame*>(
      ::ResocaMessage_CanFrame::internal_default_instance());
  ::_ResocaMessage_default_instance_._instance.get_mutable()->resocainfo_ = const_cast< ::ResocaMessage_ResocaInfo*>(
      ::ResocaMessage_ResocaInfo::internal_default_instance());
}
class ResocaMessage::_Internal {
 public:
  static const ::ResocaMessage_CanFrame& canframe(const ResocaMessage* msg);
  static const ::ResocaMessage_ResocaInfo& resocainfo(const ResocaMessage* msg);
};

const ::ResocaMessage_CanFrame&
ResocaMessage::_Internal::canframe(const ResocaMessage* msg) {
  return *msg->canframe_;
}
const ::ResocaMessage_ResocaInfo&
ResocaMessage::_Internal::resocainfo(const ResocaMessage* msg) {
  return *msg->resocainfo_;
}
ResocaMessage::ResocaMessage()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ResocaMessage)
}
ResocaMessage::ResocaMessage(const ResocaMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  interface_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_interface().empty()) {
    interface_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.interface_);
  }
  if (from._internal_has_canframe()) {
    canframe_ = new ::ResocaMessage_CanFrame(*from.canframe_);
  } else {
    canframe_ = nullptr;
  }
  if (from._internal_has_resocainfo()) {
    resocainfo_ = new ::ResocaMessage_ResocaInfo(*from.resocainfo_);
  } else {
    resocainfo_ = nullptr;
  }
  messagetype_ = from.messagetype_;
  // @@protoc_insertion_point(copy_constructor:ResocaMessage)
}

void ResocaMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResocaMessage_ResocaMessage_2eproto.base);
  interface_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&canframe_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&messagetype_) -
      reinterpret_cast<char*>(&canframe_)) + sizeof(messagetype_));
}

ResocaMessage::~ResocaMessage() {
  // @@protoc_insertion_point(destructor:ResocaMessage)
  SharedDtor();
}

void ResocaMessage::SharedDtor() {
  interface_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete canframe_;
  if (this != internal_default_instance()) delete resocainfo_;
}

void ResocaMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResocaMessage& ResocaMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResocaMessage_ResocaMessage_2eproto.base);
  return *internal_default_instance();
}


void ResocaMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ResocaMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  interface_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && canframe_ != nullptr) {
    delete canframe_;
  }
  canframe_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && resocainfo_ != nullptr) {
    delete resocainfo_;
  }
  resocainfo_ = nullptr;
  messagetype_ = 0;
  _internal_metadata_.Clear();
}

const char* ResocaMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .ResocaMessage.MessageType messageType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_messagetype(static_cast<::ResocaMessage_MessageType>(val));
        } else goto handle_unusual;
        continue;
      // string interface = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_interface();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ResocaMessage.interface"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .ResocaMessage.CanFrame canFrame = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_canframe(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .ResocaMessage.ResocaInfo resocaInfo = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_resocainfo(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResocaMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResocaMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ResocaMessage.MessageType messageType = 1;
  if (this->messagetype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_messagetype(), target);
  }

  // string interface = 2;
  if (this->interface().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_interface().data(), static_cast<int>(this->_internal_interface().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ResocaMessage.interface");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_interface(), target);
  }

  // .ResocaMessage.CanFrame canFrame = 3;
  if (this->has_canframe()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::canframe(this), target, stream);
  }

  // .ResocaMessage.ResocaInfo resocaInfo = 4;
  if (this->has_resocainfo()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::resocainfo(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResocaMessage)
  return target;
}

size_t ResocaMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResocaMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string interface = 2;
  if (this->interface().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_interface());
  }

  // .ResocaMessage.CanFrame canFrame = 3;
  if (this->has_canframe()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *canframe_);
  }

  // .ResocaMessage.ResocaInfo resocaInfo = 4;
  if (this->has_resocainfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *resocainfo_);
  }

  // .ResocaMessage.MessageType messageType = 1;
  if (this->messagetype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_messagetype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResocaMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ResocaMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const ResocaMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResocaMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ResocaMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ResocaMessage)
    MergeFrom(*source);
  }
}

void ResocaMessage::MergeFrom(const ResocaMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResocaMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.interface().size() > 0) {

    interface_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.interface_);
  }
  if (from.has_canframe()) {
    _internal_mutable_canframe()->::ResocaMessage_CanFrame::MergeFrom(from._internal_canframe());
  }
  if (from.has_resocainfo()) {
    _internal_mutable_resocainfo()->::ResocaMessage_ResocaInfo::MergeFrom(from._internal_resocainfo());
  }
  if (from.messagetype() != 0) {
    _internal_set_messagetype(from._internal_messagetype());
  }
}

void ResocaMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ResocaMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResocaMessage::CopyFrom(const ResocaMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResocaMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResocaMessage::IsInitialized() const {
  return true;
}

void ResocaMessage::InternalSwap(ResocaMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  interface_.Swap(&other->interface_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(canframe_, other->canframe_);
  swap(resocainfo_, other->resocainfo_);
  swap(messagetype_, other->messagetype_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResocaMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ResocaMessage_ResocaInfo* Arena::CreateMaybeMessage< ::ResocaMessage_ResocaInfo >(Arena* arena) {
  return Arena::CreateInternal< ::ResocaMessage_ResocaInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ResocaMessage_CanFrame* Arena::CreateMaybeMessage< ::ResocaMessage_CanFrame >(Arena* arena) {
  return Arena::CreateInternal< ::ResocaMessage_CanFrame >(arena);
}
template<> PROTOBUF_NOINLINE ::ResocaMessage* Arena::CreateMaybeMessage< ::ResocaMessage >(Arena* arena) {
  return Arena::CreateInternal< ::ResocaMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
